version: '3.8'

services:
  mcp-notify-reviewers:
    build: .
    image: ghcr.io/doraemon0905/mcp-notify-reviewers:latest
    container_name: mcp-notify-reviewers
    environment:
      - NODE_ENV=production
      - CUSTOM_API_URL=${CUSTOM_API_URL}
    stdin_open: true
    tty: true
    restart: unless-stopped 
