version: '3.8'

services:
  mcp-notify-reviewers:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ~/.cursor/mcp:/app/mcp
    environment:
      - NODE_ENV=production
      - MCP_PORT=3000
    restart: unless-stopped 
