version: '3.8'

services:
  mcp-notify-reviewers:
    build: .
    container_name: mcp-notify-reviewers
    environment:
      - NODE_ENV=production
      - MCP_PORT=3000
      - CUSTOM_API_URL=${CUSTOM_API_URL}
      - CUSTOM_API_TOKEN=${CUSTOM_API_TOKEN}
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 
